build.yml: fixup
Change-Id: I2b6e76658b616cf4c4f5504c2eb16b891edee75d
Signed-off-by: gyabii <gyabii@proton.me>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -80,9 +80,11 @@ jobs:
           ./scripts/download_fw.sh --ignore-target
           echo "- Processing SM-S911B firmware with EUX CSC"
           echo "    - Downloading ${{ github.event.inputs.triplet }}..."
-          wget -q --no-check-certificate --content-disposition "${{ github.event.inputs.url }}" --directory-prefix="./out/odin/SM-S911B_EUX"
+          wget -q --no-check-certificate --content-disposition "${{ github.event.inputs.url }}" --directory-prefix="./out/odin/SM-S911B_EUX" || echo "Firmware download failed" && exit 1
           echo "${{ github.event.inputs.triplet }}" >> "./out/odin/SM-S911B_EUX/.downloaded"
-          echo "- Firmware downloaded"
+          ZIP_FILE="$(find "out/odin/SM-S911B_EUX" -name "*.zip" | sort -r | head -n 1)"
+          echo "- Extracting $(basename "$ZIP_FILE")..."
+          unzip -o "$ZIP_FILE" -d "out/odin/SM-S911B_EUX" && rm -rf "$ZIP_FILE"
 
       - name: Extract stock firmwares
         run: |
